### PR TITLE
Google Maps Integration and Data updates

### PR DESCRIPTION
**Pull request by QuestofIranon**
The biggest change here is that I integrated Google maps. Instead of doing pure Google maps or a seperate set of files for each map type I made it an interactive option which can be switched by the user at any time. 

I didn't like having the seperate but nearly identical files because it would be a nuisance to modify and maintain. Most of the JS was identical for both google maps and leaflet integration as well so I just seperated map creation process into seperate functions.

I have also added in the values from @Bcarlson92's excel file and added the excel file to repository for future reference or need.

@rlh-aagis: If you merge this pull request you should probably restart the merging process instead of using what we did before.

### CODE REVIEW

**Comment by rlh-aagis** [comment]
Hi Josh, I was getting an error when loading in both Chrome and Firefox, not certain if it is just me or a code error. Also, we might spell check the opening modal. I didn't have time to work on it...

**Comment by zmon** [comment]
Sorry I did not see that it had not been merged... The error I get in FireFox's console is "NetworkError: 404 Not Found - http://umkc-law.github.io/Parcel-Assessment-Tool/css/images/ui-bg_flat_75_ffffff_40x100.png"  The app does run. @QuestofIranon

**Comment by QuestofIranon** [comment]
I fixed the missing images, I had that image folder in the root instead of the css directory. I also changed the text in the modal to better reflect usage. I believe I have caught any grammatical and spelling errors but would appreciate a second check.

**Comment by QuestofIranon** [comment]
It's not part of the repo but I limited the land bank data to the Wendell Phillips neighborhood and removed the zoning layer on cartodb.

**Comment by rlh-aagis** [comment]
@QuestofIranon When you say you "removed the Zoning layer in CartoDb", you only removed the layer on the map and not the dataset, correct?

**Comment by zmon** [comment]
@QuestofIranon @rlh-aagis why did we switch to Google Maps?

**Comment by rlh-aagis** [comment]
We were able to get search address eautocomplete

**Comment by rlh-aagis** [comment]
To work with google and we could use Streetview functionality

**Comment by QuestofIranon** [comment]
Yes, only the layer was removed from the code4kc cartodb.
Google Maps allows street view and has a richer API so it is more beneficial to work with. I left leaflet in for now because Cartodb is more compatible with it.

**Pull request merged**
